// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rider.Infrastructure.Persistence;

#nullable disable

namespace Rider.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RiderDbContext))]
    partial class RiderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Rider.Domain.Domain.RiderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RiderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1645, Alabama",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1646, Alabama",
                            Name = "John Peter"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1647, Alabama",
                            Name = "Peter Joe"
                        },
                        new
                        {
                            Id = 4,
                            Address = "1648, Alabama",
                            Name = "Jane Foster"
                        },
                        new
                        {
                            Id = 5,
                            Address = "1649, Alabama",
                            Name = "Daniel Kraig"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
